spring.datasource.url=jdbc:postgresql://localhost:5432/cactus_shop
spring.datasource.username=postgres
spring.datasource.password=polonia12

# Spring Boot va crea sau actualiza automat tabelele in baza de date
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect